### PR TITLE
Many chat fixes

### LINKED ISSUE #1465: After joining a group: error `conversation.send is not a function`
Just after accepting the invite to a group, the user sends a first message, and this happens:
- The message is not sent
- It fails on the UI with the error `conversation.send is not a function (it is undefined)`

## Log output
```
 LOG  10:44:17 | DEBUG : Getting token
 LOG  10:44:17 | DEBUG : [XMTPRN Contacts] Consented to groups on protocol in 0.035 sec
 LOG  10:44:19 | ERROR : conversation.send is not a function (it is undefined)
 LOG  10:44:19 | INFO : [refetchConversationMessages] refetching messages
 LOG  10:44:19 | INFO : [useConversationMessages] queryFn fetching messages by topic
 LOG  10:44:19 | DEBUG : [XMTPRN Conversations] Getting conversation by /xmtp/mls/1/g-6ff173d94f797d2907e39478dd74933a/proto
 LOG  10:44:19 | ERROR : conversation.send is not a function (it is undefined)
`````

### PR DESCRIPTION
**Pull request by thierryskoda**
Closes #1465

## Summary by CodeRabbit

Based on the comprehensive summary of changes, here are the high-level release notes:

- **New Features**
    - Added support for conversation message status tracking
    - Introduced new emoji picker functionality for conversation messages
    - Enhanced conversation message layout with system message detection

- **Improvements**
    - Refined conversation list navigation and rendering
    - Updated theme color palette with new green color
    - Improved error handling and logging mechanisms

- **UI/UX Updates**
    - Updated conversation message animations
    - Adjusted header and avatar styling
    - Simplified conversation list components

- **Performance**
    - Replaced FlashList with FlatList for better rendering
    - Optimized component memoization and theme integration

- **Maintenance**
    - Removed deprecated navigation components
    - Cleaned up unused hooks and context management
    - Updated type definitions and naming conventions

### CODE REVIEW

**Review by lourou — APPROVED** [review]

File: utils/xmtpRN/messages.ts [hunk 1]
```diff
@@ -17,6 +17,10 @@ import {
 } from "./client.types";
 import { getXmtpClient } from "./sync";
 
+export function isSupportedMessage(message: DecodedMessageWithCodecsType) {
+  return true;
```
Comment (alexrisch) [inline utils/xmtpRN/messages.ts:21]: This should be cleaned up

**Comment by technoplato** [comment]
What was the fix for send @thierryskoda ? Can you point me to some lines? Maybe in the future it would be awesome if we could separate functional fixes from UI just so they’re more clear. Love the cursor rules and will definitely be a good asset for us to share!

File: utils/xmtpRN/messages.ts (hunk 1 above)
Comment (thierryskoda) [reply utils/xmtpRN/messages.ts:21]: ah yes this is WIP my bad, forgot to add comments

**Comment by thierryskoda** [comment]
@technoplato hey yes it's here https://github.com/ephemeraHQ/converse-app/pull/1468/files#diff-33799b229dfef82c3ac6eb0bd7865bdfc5b9e0759c29b9ae6a48606ef6682fd0

Also posted in Slack. Good call that it could happen again

**Review by alexrisch — APPROVED** [review]
