### PR TITLE
bugfix: emoji picker/reaction icons cut-off on Android

### LINKED ISSUE #1146: Bug: Long press on Galaxy reaction menu is cut off
### Describe the bug

Seen in 2.0.7, should fix for 2.0.8

image

### PR DESCRIPTION
**Pull request by lourou**
- Fix emoji picker emoji icons cut-off on Android Galaxy (tested from API 30 to 34 on 5 devices)
- Tested for iOS regression
- Migrate to the design system theme and apply the new emoji picker bubble design

Note: this closes #1146 – the rest of the `MessageContextMenu` component needs design system migration and refactor, I'll be working on this and submit it in another PR.

### CODE REVIEW

File: components/Chat/Message/MessageReactionsList.tsx [hunk 1]
```diff
@@ -6,13 +6,9 @@ import {
...
 import { useSelect } from "@data/store/storeHelpers";
-import {
-  backgroundColor,
-  textPrimaryColor,
-  textSecondaryColor,
-  tertiaryBackgroundColor,
-} from "@styles/colors";
-import { AvatarSizes, BorderRadius, Paddings, Margins } from "@styles/sizes";
+import { backgroundColor, textSecondaryColor } from "@styles/colors";
+import { AvatarSizes, BorderRadius } from "@styles/sizes";
```
Comment (thierryskoda) [inline components/Chat/Message/MessageReactionsList.tsx:10]: While working on the reactions do you think you could remove the deprecated stuff? 😮 

If it's out of the scope no worries

File: components/Chat/Message/MessageReactionsList.tsx [hunk 2]
```diff
@@ -153,7 +152,7 @@ const EmojiItem: FC<{
           alreadySelected && styles.selectedEmojiText,
         ]}
       >
-        <Text style={styles.emojiText}>{content}</Text>
+        <Text style={{ fontSize: 22, lineHeight: 28 }}>{content}</Text>
```
Comment (thierryskoda) [inline components/Chat/Message/MessageReactionsList.tsx:155]: Should we create a new text preset for this in Text component?

Comment (lourou) [reply components/Chat/Message/MessageReactionsList.tsx]: @thierryskoda yes, great idea! love this preset feature. This is done!

**Review by thierryskoda — APPROVED** [review]

**Review by alexrisch — APPROVED** [review]

**Review by alexrisch — APPROVED** [review]
